---
name: Build

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
          path: rtl_433_win


      # WINDOWS
      - name: Install dependencies
        shell: pwsh
        run: |
          cd ..
          Invoke-WebRequest -Uri "https://github.com/JetBrains/kotlin/releases/download/v1.3.72/kotlin-native-windows-1.3.72.zip" -OutFile kotlin-native-windows-1.3.72.zip
          &7z x kotlin-native-windows-1.3.72.zip -okotlin-native
          Remove-Item librtlsdr_0.6.0_win64_2019-08-19.zip
          kotlin-native/kotlinc-native hello.kt -o hello.exe 
