name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      # WINDOWS
      - name: Install dependencies
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/JetBrains/kotlin/releases/download/v1.3.72/kotlin-native-windows-1.3.72.zip" -OutFile kotlin-native-windows-1.3.72.zip
          &7z x kotlin-native-windows-1.3.72.zip
         
         
      - name: Build (Windows)
        run: |
            dir
            cd kotlin-native-windows-1.3.72\bin
            dir
            kotlinc-native ..\..\hello.kt -o hello.exe -target mingw_x86
            dir
            kotlinc-native ..\..\hello.kt -o hello.exe -target mingw_x86
            
        shell: cmd
