name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      # WINDOWS
      - name: Install dependencies
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/JetBrains/kotlin/releases/download/v1.3.72/kotlin-native-windows-1.3.72.zip" -OutFile kotlin-native-windows-1.3.72.zip
          &7z x kotlin-native-windows-1.3.72.zip -okotlin-native
          Remove-Item librtlsdr_0.6.0_win64_2019-08-19.zip
         
      - name: Build (Windows)
        if: startsWith(matrix.os, 'windows')
        run: |
            kotlin-native\kotlinc-native hello.kt -o hello.exe
            
        shell: cmd
